/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXTPROFILE_FIXES_H__
#define __EXTPROFILE_FIXES_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_fixes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline int64 x_cal_days_in_month(int64 calendar, int64 month, int64 year) {
  FUNCTION_INJECTION_BUILTIN(cal_days_in_month);
  return f_cal_days_in_month(calendar, month, year);
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_FIXES_H__
