/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXTPROFILE_GETTEXT_H__
#define __EXTPROFILE_GETTEXT_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_gettext.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline Variant x_textdomain(CStrRef domain) {
  FUNCTION_INJECTION_BUILTIN(textdomain);
  return f_textdomain(domain);
}

inline Variant x_gettext(CStrRef msgid) {
  FUNCTION_INJECTION_BUILTIN(gettext);
  return f_gettext(msgid);
}

inline Variant x_dgettext(CStrRef domain_name, CStrRef msgid) {
  FUNCTION_INJECTION_BUILTIN(dgettext);
  return f_dgettext(domain_name, msgid);
}

inline Variant x_dcgettext(CStrRef domain_name, CStrRef msgid, int64 category) {
  FUNCTION_INJECTION_BUILTIN(dcgettext);
  return f_dcgettext(domain_name, msgid, category);
}

inline Variant x_bindtextdomain(CStrRef domain_name, CStrRef dir) {
  FUNCTION_INJECTION_BUILTIN(bindtextdomain);
  return f_bindtextdomain(domain_name, dir);
}

inline Variant x_ngettext(CStrRef msg, CStrRef msg_plural, int64 n) {
  FUNCTION_INJECTION_BUILTIN(ngettext);
  return f_ngettext(msg, msg_plural, n);
}

inline Variant x_dngettext(CStrRef domain, CStrRef msg, CStrRef msg_plural, int64 n) {
  FUNCTION_INJECTION_BUILTIN(dngettext);
  return f_dngettext(domain, msg, msg_plural, n);
}

inline Variant x_dcngettext(CStrRef domain, CStrRef msg, CStrRef msg_plural, int64 n, int64 category) {
  FUNCTION_INJECTION_BUILTIN(dcngettext);
  return f_dcngettext(domain, msg, msg_plural, n, category);
}

inline Variant x_bind_textdomain_codeset(CStrRef domain, CStrRef codeset) {
  FUNCTION_INJECTION_BUILTIN(bind_textdomain_codeset);
  return f_bind_textdomain_codeset(domain, codeset);
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_GETTEXT_H__
