/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXTPROFILE_USERPARTITION_H__
#define __EXTPROFILE_USERPARTITION_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_userpartition.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline Variant x_get_tuenti_user_partition(int64 user_id) {
  FUNCTION_INJECTION_BUILTIN(get_tuenti_user_partition);
  return f_get_tuenti_user_partition(user_id);
}

inline bool x_set_tuenti_user_partition(int64 user_id, int64 partition_id) {
  FUNCTION_INJECTION_BUILTIN(set_tuenti_user_partition);
  return f_set_tuenti_user_partition(user_id, partition_id);
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_USERPARTITION_H__
