/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/
/**
 * Extension to add cache to json decoding
 *
 * LICENSE: This file can only be stored on servers belonging to Tuenti Technologies S.L.
 *
 * @copyright 2011, (c) Tuenti Technologies S.L.
 * @author Daniel Pañeda <dpaneda@tuenti.com>
 */ 

#ifndef __EXT_TUENTI_JSONLOADER_H__
#define __EXT_TUENTI_JSONLOADER_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {

enum JsonEntry {
    JSON = 0,
    LAST_UPDATE,
    LAST_UPDATE_NSECS,
    LAST_CHECK,
};

/**
 * 
 * Wrapper over json_decode to add cache based on time of last modification of
 * the file. See json_decode for a further description of params
 *
 * @param string json_file
 * @param bool assoc
 * @param bool loose
 * @return Array with:
 *      - Variant decoded_json  Decoded json 
 *      - int last_modified     Time of last modification of the json file
 *      - int last_checked      Last time the json file modification time was checked
 */
Variant f_cached_json_decode(CStrRef json_file, bool assoc = false, bool loose = false);
}

#endif // __EXT_TUENTI_JSONLOADER_H__
