/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_BUCKETCACHE_H__
#define __EXT_BUCKETCACHE_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

Variant f_get_bucket_cache_info(int64 cluster_id, int64 bucket_id);
bool f_set_bucket_cache_info(int64 cluster_id, int64 bucket_id, int64 state, int64 server, int64 volume, int64 alt_server, int64 alt_volume);
extern const int64 k_BUCKET_INFO_CLUSTER;
extern const int64 k_BUCKET_INFO_ID;
extern const int64 k_BUCKET_INFO_STATE;
extern const int64 k_BUCKET_INFO_SERVER;
extern const int64 k_BUCKET_INFO_VOLUME;
extern const int64 k_BUCKET_INFO_ALT_SERVER;
extern const int64 k_BUCKET_INFO_ALT_VOLUME;

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_BUCKETCACHE_H__
