/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_FILEINFO_H__
#define __EXT_FILEINFO_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

extern const int64 k_FILEINFO_NONE;
extern const int64 k_FILEINFO_SYMLINK;
extern const int64 k_FILEINFO_MIME;
extern const int64 k_FILEINFO_MIME_TYPE;
extern const int64 k_FILEINFO_MIME_ENCODING;
extern const int64 k_FILEINFO_DEVICES;
extern const int64 k_FILEINFO_CONTINUE;
extern const int64 k_FILEINFO_PRESERVE_ATIME;
extern const int64 k_FILEINFO_RAW;

Variant f_finfo_open(int64 options = k_FILEINFO_NONE, CStrRef magic_file = null_string);
Variant f_finfo_close(CObjRef finfo);
Variant f_finfo_buffer(CObjRef finfo, CStrRef buffer = null_string, int64 options = k_FILEINFO_NONE, CStrRef context = null_string);
Variant f_finfo_file(CObjRef finfo, CStrRef file_name = null_string, int64 options = k_FILEINFO_NONE, CStrRef context = null_string);
Variant f_finfo_set_flags(CObjRef finfo, int64 options = k_FILEINFO_NONE);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_FILEINFO_H__
