/*
   +----------------------------------------------------------------------+
   | HipHop for PHP                                                       |
   +----------------------------------------------------------------------+
   | Copyright (c) 2010- Facebook, Inc. (http://www.facebook.com)         |
   | Copyright (c) 1997-2010 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
*/

#ifndef __EXT_GEOIP_H__
#define __EXT_GEOIP_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

#include <GeoIP.h>
#include <GeoIPCity.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

extern const int64 k_GEOIP_COUNTRY_EDITION;
extern const int64 k_GEOIP_REGION_EDITION_REV0;
extern const int64 k_GEOIP_CITY_EDITION_REV0;
extern const int64 k_GEOIP_ORG_EDITION;
extern const int64 k_GEOIP_ISP_EDITION;
extern const int64 k_GEOIP_CITY_EDITION_REV1;
extern const int64 k_GEOIP_REGION_EDITION_REV1;
extern const int64 k_GEOIP_PROXY_EDITION;
extern const int64 k_GEOIP_ASNUM_EDITION;
extern const int64 k_GEOIP_NETSPEED_EDITION;
extern const int64 k_GEOIP_DOMAIN_EDITION;
extern const int64 k_GEOIP_UNKNOWN_SPEED;
extern const int64 k_GEOIP_DIALUP_SPEED;
extern const int64 k_GEOIP_CABLEDSL_SPEED;
extern const int64 k_GEOIP_CORPORATE_SPEED;
extern const int64 k_GEOIP_STANDARD;
extern const int64 k_GEOIP_MEMORY_CACHE;
extern const int64 k_GEOIP_CHECK_CACHE;
extern const int64 k_GEOIP_INDEX_CACHE;
extern const int64 k_GEOIP_MMAP_CACHE;

Variant f_geoip_db_avail(int64 database);
Variant f_geoip_db_filename(int64 database);
Array f_geoip_db_get_all_info();
Variant f_geoip_database_info(int64 database = k_GEOIP_COUNTRY_EDITION);
Variant f_geoip_country_code_by_name(CStrRef hostname);
Variant f_geoip_country_code3_by_name(CStrRef hostname);
Variant f_geoip_country_name_by_name(CStrRef hostname);
Variant f_geoip_continent_code_by_name(CStrRef hostname);
Variant f_geoip_org_by_name(CStrRef hostname);
Array f_geoip_record_by_name(CStrRef hostname);
Variant f_geoip_id_by_name(CStrRef hostname);
Array f_geoip_region_by_name(CStrRef hostname);
Variant f_geoip_isp_by_name(CStrRef hostname);
Variant f_geoip_region_name_by_code(CStrRef country_code, CStrRef region_code);
Variant f_geoip_time_zone_by_country_and_region(CStrRef country_code, CStrRef region_code = null_string);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_GEOIP_H__
