#
# $Id$
#
# - Find pcre
# Find the native PCRE includes and library
#
#  PCRE_INCLUDE_DIRS - where to find pcre.h, etc.
#  PCRE_LIBRARIES    - List of libraries when using pcre.
#  PCRE_FOUND        - True if pcre found.


IF (PCRE_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(PCRE_FIND_QUIETLY TRUE)
ENDIF (PCRE_INCLUDE_DIRS)

FIND_PATH(PCRE_INCLUDE_DIR pcre.h)

SET(PCRE_NAMES pcre)
SET(PCRE_POSIX_NAMES pcreposix)
FIND_LIBRARY(PCRE_LIBRARY NAMES ${PCRE_NAMES} )
FIND_LIBRARY(PCRE_POSIX_LIBRARY NAMES ${PCRE_POSIX_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set PCRE_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE DEFAULT_MSG PCRE_LIBRARY PCRE_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRE_POSIX DEFAULT_MSG PCRE_POSIX_LIBRARY PCRE_POSIX_INCLUDE_DIR)

IF(PCRE_FOUND)
  SET( PCRE_LIBRARIES ${PCRE_LIBRARY} )
  SET( PCRE_INCLUDE_DIRS ${PCRE_INCLUDE_DIR} )
ELSE(PCRE_FOUND)
  SET( PCRE_LIBRARIES )
  SET( PCRE_INCLUDE_DIRS )
ENDIF(PCRE_FOUND)
IF(PCRE_POSIX_FOUND)
  SET( PCRE_POSIX_LIBRARIES ${PCRE_POSIX_LIBRARY} )
ELSE(PCRE_POSIX_FOUND)
  SET( PCRE_POSIX_LIBRARIES )
ENDIF(PCRE_POSIX_FOUND)

MARK_AS_ADVANCED( PCRE_LIBRARIES PCRE_POSIX_LIBRARY PCRE_INCLUDE_DIRS )
